name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          E2E_ENV: "Dev"
          AGENT_USERNAME: ${{ secrets.DEV_AGENT_USERNAME }}
          AGENT_PASSWORD: ${{ secrets.DEV_AGENT_PASSWORD }}
          AGENT_ID: ${{ secrets.DEV_AGENT_ID }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-playwright-parallel-${{ matrix.NODE_INDEX }}
          path: allure-results
