name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install 

    - name: Run Playwright tests
      # env:
      #   E2E_ENV : 'Dev'

      run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-playwright-parallel-${{ matrix.NODE_INDEX }}
          path: allure-results
